version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: porty_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: porty_db
      POSTGRES_USER: porty_user
      POSTGRES_PASSWORD: porty_pass
    ports:
      - "5432:5432"
    volumes:
      - porty_data:/var/lib/postgresql/data

volumes:
  porty_data: