spring:
  application:
    name: portyj
  datasource:
    url: jdbc:postgresql://localhost:5432/porty_db
    username: porty_user
    password: porty_pass
    driver-class-name: org.postgresql.Driver
